In [1]:
print("Disease Prediction AI")

Disease Prediction AI

In [2]:
import pandas as pd
import numpy as np
import sklearn
import matplotlib
import seaborn

print("Pandas:", pd.__version__)
print("NumPy:", np.__version__)
print("Scikit-learn:", sklearn.__version__)
print("Matplotlib:", matplotlib.__version__)
print("Seaborn:", seaborn.__version__)

Pandas: 3.0.6
NumPy: 2.5.3
Scikit-learn: 1.9.1
Matplotlib: 3.11.2
Seaborn: 0.13.2

In [4]:
import pandas as pd
df=pd.read_csv("../data/diabetes_data_upload.csv")
df.head()

,Age,Gender,Polyuria,Polydipsia,sudden weight loss,weakness,Polyphagia,Genital thrush,visual blurring,Itching,Irritability,delayed healing,partial paresis,muscle stiffness,Alopecia,Obesity,class
0,40,Male,No,Yes,No,Yes,No,No,No,Yes,No,Yes,No,Yes,Yes,Yes,Positive
1,58,Male,No,No,No,Yes,No,No,Yes,No,No,No,Yes,No,Yes,No,Positive
2,41,Male,Yes,No,No,Yes,Yes,No,No,Yes,No,Yes,No,Yes,Yes,No,Positive
3,45,Male,No,No,Yes,Yes,Yes,Yes,No,Yes,No,Yes,No,No,No,No,Positive
4,60,Male,Yes,Yes,Yes,Yes,Yes,No,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Positive

In [8]:
df.shape
df.columns.tolist()
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 520 entries, 0 to 519
Data columns (total 17 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Age                 520 non-null    int64
 1   Gender              520 non-null    str
 2   Polyuria            520 non-null    str
 3   Polydipsia          520 non-null    str
 4   sudden weight loss  520 non-null    str
 5   weakness            520 non-null    str
 6   Polyphagia          520 non-null    str
 7   Genital thrush      520 non-null    str
 8   visual blurring     520 non-null    str
 9   Itching             520 non-null    str
 10  Irritability        520 non-null    str
 11  delayed healing     520 non-null    str
 12  partial paresis     520 non-null    str
 13  muscle stiffness    520 non-null    str
 14  Alopecia            520 non-null    str
 15  Obesity             520 non-null    str
 16  class               520 non-null    str
dtypes: int64(1), str(16)
memory usage: 92.7 KB

In [9]:
df.isnull().sum()

Age                   0
Gender                0
Polyuria              0
Polydipsia            0
sudden weight loss    0
weakness              0
Polyphagia            0
Genital thrush        0
visual blurring       0
Itching               0
Irritability          0
delayed healing       0
partial paresis       0
muscle stiffness      0
Alopecia              0
Obesity               0
class                 0
dtype: int64

In [11]:
df.duplicated().sum()

np.int64(269)

In [12]:
df[df.duplicated()].head(10)

,Age,Gender,Polyuria,Polydipsia,sudden weight loss,weakness,Polyphagia,Genital thrush,visual blurring,Itching,Irritability,delayed healing,partial paresis,muscle stiffness,Alopecia,Obesity,class
84,35,Female,Yes,Yes,Yes,Yes,Yes,No,Yes,Yes,No,Yes,Yes,Yes,No,No,Positive
159,38,Female,Yes,Yes,Yes,Yes,Yes,No,Yes,Yes,Yes,Yes,Yes,Yes,No,No,Positive
160,28,Female,No,No,No,No,No,No,Yes,No,No,No,Yes,Yes,No,No,Positive
161,68,Female,Yes,Yes,No,Yes,Yes,No,Yes,Yes,No,Yes,Yes,No,No,No,Positive
162,35,Female,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Positive
163,45,Female,No,No,No,No,Yes,No,Yes,Yes,No,No,Yes,No,No,No,Positive
164,48,Female,Yes,Yes,Yes,Yes,Yes,No,Yes,Yes,Yes,Yes,Yes,Yes,No,No,Positive
165,40,Female,Yes,Yes,Yes,Yes,No,No,Yes,No,No,Yes,Yes,Yes,No,No,Positive
166,57,Male,Yes,Yes,Yes,Yes,Yes,No,Yes,No,No,No,Yes,No,No,No,Positive
167,41,Male,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,No,No,No,No,Yes,Positive

In [13]:
df[df.duplicated()].shape

(269, 17)

In [14]:
df["class"].value_counts(normalize=True) * 100

class
Positive    61.538462
Negative    38.461538
Name: proportion, dtype: float64

In [17]:
df.nunique()

Age                   51
Gender                 2
Polyuria               2
Polydipsia             2
sudden weight loss     2
weakness               2
Polyphagia             2
Genital thrush         2
visual blurring        2
Itching                2
Irritability           2
delayed healing        2
partial paresis        2
muscle stiffness       2
Alopecia               2
Obesity                2
class                  2
dtype: int64

In [15]:
for column in df.columns:
    print("\n", column)
    print(df[column].unique())

 Age
[40 58 41 45 60 55 57 66 67 70 44 38 35 61 54 43 62 39 48 32 42 52 53 37
 49 63 30 50 46 36 51 59 65 25 47 28 68 56 31 85 90 72 69 79 34 16 33 64
 27 29 26]

 Gender
<ArrowStringArray>
['Male', 'Female']
Length: 2, dtype: str

 Polyuria
<ArrowStringArray>
['No', 'Yes']
Length: 2, dtype: str

 Polydipsia
<ArrowStringArray>
['Yes', 'No']
Length: 2, dtype: str

 sudden weight loss
<ArrowStringArray>
['No', 'Yes']
Length: 2, dtype: str

 weakness
<ArrowStringArray>
['Yes', 'No']
Length: 2, dtype: str

 Polyphagia
<ArrowStringArray>
['No', 'Yes']
Length: 2, dtype: str

 Genital thrush
<ArrowStringArray>
['No', 'Yes']
Length: 2, dtype: str

 visual blurring
<ArrowStringArray>
['No', 'Yes']
Length: 2, dtype: str

 Itching
<ArrowStringArray>
['Yes', 'No']
Length: 2, dtype: str

 Irritability
<ArrowStringArray>
['No', 'Yes']
Length: 2, dtype: str

 delayed healing
<ArrowStringArray>
['Yes', 'No']
Length: 2, dtype: str

 partial paresis
<ArrowStringArray>
['No', 'Yes']
Length: 2, dtype: str

 muscle stiffness
<ArrowStringArray>
['Yes', 'No']
Length: 2, dtype: str

 Alopecia
<ArrowStringArray>
['Yes', 'No']
Length: 2, dtype: str

 Obesity
<ArrowStringArray>
['Yes', 'No']
Length: 2, dtype: str

 class
<ArrowStringArray>
['Positive', 'Negative']
Length: 2, dtype: str

In [16]:
df["Age"].describe()

count    520.000000
mean      48.028846
std       12.151466
min       16.000000
25%       39.000000
50%       47.500000
75%       57.000000
max       90.000000
Name: Age, dtype: float64

In [18]:
clean_df = df.copy()

In [19]:
clean_df.duplicated().sum()

np.int64(269)

In [20]:
clean_df = clean_df.drop_duplicates().reset_index(drop=True)

In [21]:
clean_df.shape

(251, 17)

In [22]:
clean_df.duplicated().sum()

np.int64(0)

In [24]:
clean_df["class"].value_counts()
clean_df["class"].value_counts(normalize=True) * 100

class
Positive    68.924303
Negative    31.075697
Name: proportion, dtype: float64

#converting yesno in the numbers

In [25]:
feature_columns = [
    column for column in clean_df.columns
    if column not in ["Age", "class"]
]

feature_columns

['Gender',
 'Polyuria',
 'Polydipsia',
 'sudden weight loss',
 'weakness',
 'Polyphagia',
 'Genital thrush',
 'visual blurring',
 'Itching',
 'Irritability',
 'delayed healing',
 'partial paresis',
 'muscle stiffness',
 'Alopecia',
 'Obesity']

In [26]:
clean_df[feature_columns] = clean_df[feature_columns].replace({
    "Yes": 1,
    "No": 0
})

In [27]:
clean_df.head()

,Age,Gender,Polyuria,Polydipsia,sudden weight loss,weakness,Polyphagia,Genital thrush,visual blurring,Itching,Irritability,delayed healing,partial paresis,muscle stiffness,Alopecia,Obesity,class
0,40,Male,0,1,0,1,0,0,0,1,0,1,0,1,1,1,Positive
1,58,Male,0,0,0,1,0,0,1,0,0,0,1,0,1,0,Positive
2,41,Male,1,0,0,1,1,0,0,1,0,1,0,1,1,0,Positive
3,45,Male,0,0,1,1,1,1,0,1,0,1,0,0,0,0,Positive
4,60,Male,1,1,1,1,1,0,1,1,1,1,1,1,1,1,Positive

#convert targets positive/negative into nnumbers

In [28]:
clean_df["class"] = clean_df["class"].replace({
    "Positive": 1,
    "Negative": 0
})

In [29]:
clean_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 251 entries, 0 to 250
Data columns (total 17 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Age                 251 non-null    int64
 1   Gender              251 non-null    str
 2   Polyuria            251 non-null    object
 3   Polydipsia          251 non-null    object
 4   sudden weight loss  251 non-null    object
 5   weakness            251 non-null    object
 6   Polyphagia          251 non-null    object
 7   Genital thrush      251 non-null    object
 8   visual blurring     251 non-null    object
 9   Itching             251 non-null    object
 10  Irritability        251 non-null    object
 11  delayed healing     251 non-null    object
 12  partial paresis     251 non-null    object
 13  muscle stiffness    251 non-null    object
 14  Alopecia            251 non-null    object
 15  Obesity             251 non-null    object
 16  class               251 non-null    object
dtypes: int64(1), object(15), str(1)
memory usage: 34.7+ KB

In [33]:
X = clean_df.drop("class", axis=1)
y = clean_df["class"]
print("X shape:", X.shape)
print("y shape:", y.shape)

X shape: (251, 16)
y shape: (251,)

In [34]:
X.head()
X.dtypes
y.head()

0    1
1    1
2    1
3    1
4    1
Name: class, dtype: object

In [35]:
clean_df["class"].value_counts()

class
1    173
0     78
Name: count, dtype: int64

In [36]:
X.dtypes

Age                    int64
Gender                   str
Polyuria              object
Polydipsia            object
sudden weight loss    object
weakness              object
Polyphagia            object
Genital thrush        object
visual blurring       object
Itching               object
Irritability          object
delayed healing       object
partial paresis       object
muscle stiffness      object
Alopecia              object
Obesity               object
dtype: object

In [37]:
for column in clean_df.columns:
    print(column, "→", clean_df[column].unique())

Age → [40 58 41 45 60 55 57 66 67 70 44 38 35 61 54 43 62 39 48 32 42 52 53 37
 49 63 30 50 46 36 51 59 65 25 47 28 68 56 31 85 90 72 69 79 34 16 33 64
 27 29 26]
Gender → <ArrowStringArray>
['Male', 'Female']
Length: 2, dtype: str
Polyuria → [0 1]
Polydipsia → [1 0]
sudden weight loss → [0 1]
weakness → [1 0]
Polyphagia → [0 1]
Genital thrush → [0 1]
visual blurring → [0 1]
Itching → [1 0]
Irritability → [0 1]
delayed healing → [1 0]
partial paresis → [0 1]
muscle stiffness → [1 0]
Alopecia → [1 0]
Obesity → [1 0]
class → [1 0]

In [38]:
symptom_columns = [
    column for column in clean_df.columns
    if column not in ["Age", "Gender", "class"]
]

for column in symptom_columns:
    clean_df[column] = clean_df[column].map({
        "Yes": 1,
        "No": 0
    })

In [39]:
clean_df["Gender"] = clean_df["Gender"].map({
    "Male": 1,
    "Female": 0
})

In [40]:
clean_df.dtypes

Age                     int64
Gender                  int64
Polyuria              float64
Polydipsia            float64
sudden weight loss    float64
weakness              float64
Polyphagia            float64
Genital thrush        float64
visual blurring       float64
Itching               float64
Irritability          float64
delayed healing       float64
partial paresis       float64
muscle stiffness      float64
Alopecia              float64
Obesity               float64
class                  object
dtype: object

In [41]:
clean_df.isnull().sum()

Age                     0
Gender                  0
Polyuria              251
Polydipsia            251
sudden weight loss    251
weakness              251
Polyphagia            251
Genital thrush        251
visual blurring       251
Itching               251
Irritability          251
delayed healing       251
partial paresis       251
muscle stiffness      251
Alopecia              251
Obesity               251
class                   0
dtype: int64

In [42]:
X = clean_df.drop("class", axis=1)
y = clean_df["class"]
print("X shape:", X.shape)
print("y shape:", y.shape)

X shape: (251, 16)
y shape: (251,)

In [43]:
clean_df.dtypes

Age                     int64
Gender                  int64
Polyuria              float64
Polydipsia            float64
sudden weight loss    float64
weakness              float64
Polyphagia            float64
Genital thrush        float64
visual blurring       float64
Itching               float64
Irritability          float64
delayed healing       float64
partial paresis       float64
muscle stiffness      float64
Alopecia              float64
Obesity               float64
class                  object
dtype: object

In [44]:
clean_df.isnull().sum()

Age                     0
Gender                  0
Polyuria              251
Polydipsia            251
sudden weight loss    251
weakness              251
Polyphagia            251
Genital thrush        251
visual blurring       251
Itching               251
Irritability          251
delayed healing       251
partial paresis       251
muscle stiffness      251
Alopecia              251
Obesity               251
class                   0
dtype: int64

In [45]:
df["Polyuria"].unique()
df["Gender"].unique()
df["Polyuria"].value_counts()

Polyuria
No     262
Yes    258
Name: count, dtype: int64

In [46]:
print(df["Polyuria"].dtype)
print(df["Gender"].dtype)

str
str

In [47]:
# ============================================
# STEP: CLEAN AND PREPARE THE DATASET
# ============================================

import pandas as pd

# 1. Start from the original dataset
clean_df = df.copy()

# 2. Remove exact duplicate rows
clean_df = clean_df.drop_duplicates().reset_index(drop=True)

# 3. Columns containing Yes/No values
yes_no_columns = [
    "Polyuria",
    "Polydipsia",
    "sudden weight loss",
    "weakness",
    "Polyphagia",
    "Genital thrush",
    "visual blurring",
    "Itching",
    "Irritability",
    "delayed healing",
    "partial paresis",
    "muscle stiffness",
    "Alopecia",
    "Obesity"
]

# 4. Convert Yes/No to 1/0
for column in yes_no_columns:
    clean_df[column] = clean_df[column].map({
        "Yes": 1,
        "No": 0
    })

# 5. Convert Gender to 1/0
clean_df["Gender"] = clean_df["Gender"].map({
    "Male": 1,
    "Female": 0
})

# 6. Convert target class to 1/0
clean_df["class"] = clean_df["class"].map({
    "Positive": 1,
    "Negative": 0
})

# 7. Check for missing values created during conversion
print("Missing values:")
print(clean_df.isnull().sum())

# 8. Check data types
print("\nData types:")
print(clean_df.dtypes)

# 9. Create X (features) and y (target)
X = clean_df.drop("class", axis=1)
y = clean_df["class"]

# 10. Print final dataset information
print("\nFinal dataset shape:")
print("X shape:", X.shape)
print("y shape:", y.shape)

# 11. Display first 5 rows
print("\nFirst 5 rows of cleaned dataset:")
display(clean_df.head())

Missing values:
Age                   0
Gender                0
Polyuria              0
Polydipsia            0
sudden weight loss    0
weakness              0
Polyphagia            0
Genital thrush        0
visual blurring       0
Itching               0
Irritability          0
delayed healing       0
partial paresis       0
muscle stiffness      0
Alopecia              0
Obesity               0
class                 0
dtype: int64

Data types:
Age                   int64
Gender                int64
Polyuria              int64
Polydipsia            int64
sudden weight loss    int64
weakness              int64
Polyphagia            int64
Genital thrush        int64
visual blurring       int64
Itching               int64
Irritability          int64
delayed healing       int64
partial paresis       int64
muscle stiffness      int64
Alopecia              int64
Obesity               int64
class                 int64
dtype: object

Final dataset shape:
X shape: (251, 16)
y shape: (251,)

First 5 rows of cleaned dataset:

,Age,Gender,Polyuria,Polydipsia,sudden weight loss,weakness,Polyphagia,Genital thrush,visual blurring,Itching,Irritability,delayed healing,partial paresis,muscle stiffness,Alopecia,Obesity,class
0,40,1,0,1,0,1,0,0,0,1,0,1,0,1,1,1,1
1,58,1,0,0,0,1,0,0,1,0,0,0,1,0,1,0,1
2,41,1,1,0,0,1,1,0,0,1,0,1,0,1,1,0,1
3,45,1,0,0,1,1,1,1,0,1,0,1,0,0,0,0,1
4,60,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1

In [48]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("X_train:", X_train.shape)
print("X_test:", X_test.shape)
print("y_train:", y_train.shape)
print("y_test:", y_test.shape)

X_train: (200, 16)
X_test: (51, 16)
y_train: (200,)
y_test: (51,)

#training the model starts

#Linear_regression_model

In [57]:
# ============================================
# FIRST MACHINE LEARNING MODEL
# Logistic Regression
# ============================================

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix
)

# 1. Create model
model = LogisticRegression(max_iter=1000)

# 2. Train model
model.fit(X_train, y_train)

print("Model training completed!")

# 3. Make predictions on unseen test data
y_pred = model.predict(X_test)

# 4. Show predictions
print("\nPredictions:")
print(y_pred)

# 5. Show actual answers
print("\nActual:")
print(y_test.to_numpy())

# 6. Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)

print("\nAccuracy:", accuracy)
print("Accuracy (%):", accuracy * 100)

# 7. Classification report
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

# 8. Confusion matrix
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Model training completed!

Predictions:
[0 1 1 1 0 0 0 1 0 1 0 0 0 1 1 1 0 0 0 1 0 0 0 0 1 1 1 0 1 1 1 1 0 1 0 1 1
 1 1 0 1 0 0 1 1 1 1 1 1 1 1]

Actual:
[0 1 0 1 1 0 0 1 0 1 1 0 0 1 1 1 1 0 1 1 1 0 1 0 1 1 1 0 1 1 1 0 0 1 0 1 1
 1 1 1 1 0 0 1 1 1 1 1 1 1 1]

Accuracy: 0.8235294117647058
Accuracy (%): 82.35294117647058

Classification Report:
              precision    recall  f1-score   support

           0       0.67      0.88      0.76        16
           1       0.93      0.80      0.86        35

    accuracy                           0.82        51
   macro avg       0.80      0.84      0.81        51
weighted avg       0.85      0.82      0.83        51


Confusion Matrix:
[[14  2]
 [ 7 28]]

In [58]:
#descision tree

In [59]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Create Decision Tree
tree_model = DecisionTreeClassifier(
    random_state=42
)

# Train
tree_model.fit(X_train, y_train)

# Predict
tree_pred = tree_model.predict(X_test)

# Accuracy
tree_accuracy = accuracy_score(y_test, tree_pred)

print("Decision Tree Accuracy:", tree_accuracy)
print("Decision Tree Accuracy (%):", tree_accuracy * 100)

print("\nClassification Report:")
print(classification_report(y_test, tree_pred))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, tree_pred))

Decision Tree Accuracy: 0.8235294117647058
Decision Tree Accuracy (%): 82.35294117647058

Classification Report:
              precision    recall  f1-score   support

           0       0.65      0.94      0.77        16
           1       0.96      0.77      0.86        35

    accuracy                           0.82        51
   macro avg       0.81      0.85      0.81        51
weighted avg       0.87      0.82      0.83        51


Confusion Matrix:
[[15  1]
 [ 8 27]]

In [60]:
#random forest

In [61]:
from sklearn.ensemble import RandomForestClassifier

# Create Random Forest
forest_model = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

# Train
forest_model.fit(X_train, y_train)

# Predict
forest_pred = forest_model.predict(X_test)

# Accuracy
forest_accuracy = accuracy_score(y_test, forest_pred)

print("Random Forest Accuracy:", forest_accuracy)
print("Random Forest Accuracy (%):", forest_accuracy * 100)

print("\nClassification Report:")
print(classification_report(y_test, forest_pred))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, forest_pred))

Random Forest Accuracy: 0.9215686274509803
Random Forest Accuracy (%): 92.15686274509804

Classification Report:
              precision    recall  f1-score   support

           0       0.80      1.00      0.89        16
           1       1.00      0.89      0.94        35

    accuracy                           0.92        51
   macro avg       0.90      0.94      0.91        51
weighted avg       0.94      0.92      0.92        51


Confusion Matrix:
[[16  0]
 [ 4 31]]

In [62]:
#5 fold stratefied cross validation

In [63]:
from sklearn.model_selection import StratifiedKFold, cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

# 5-fold stratified cross-validation
cv = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)

# Models
logistic_model = LogisticRegression(max_iter=1000)

tree_model = DecisionTreeClassifier(
    random_state=42
)

forest_model = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

# Cross-validation scores
logistic_scores = cross_val_score(
    logistic_model, X_train, y_train, cv=cv, scoring="accuracy"
)

tree_scores = cross_val_score(
    tree_model, X_train, y_train, cv=cv, scoring="accuracy"
)

forest_scores = cross_val_score(
    forest_model, X_train, y_train, cv=cv, scoring="accuracy"
)

# Print results
print("Logistic Regression:")
print(logistic_scores)
print("Mean:", logistic_scores.mean())

print("\nDecision Tree:")
print(tree_scores)
print("Mean:", tree_scores.mean())

print("\nRandom Forest:")
print(forest_scores)
print("Mean:", forest_scores.mean())

Logistic Regression:
[0.9   0.85  0.9   0.925 0.875]
Mean: 0.89

Decision Tree:
[0.75  0.9   0.875 0.9   0.8  ]
Mean: 0.845

Random Forest:
[0.9  0.95 0.95 0.95 0.9 ]
Mean: 0.93

In [64]:
# ============================================
# RANDOM FOREST HYPERPARAMETER TUNING
# ============================================

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV, StratifiedKFold

# 5-fold stratified cross-validation
cv = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)

# Base Random Forest
rf = RandomForestClassifier(
    random_state=42
)

# Hyperparameters we want to test
param_grid = {
    "n_estimators": [50, 100, 200],
    "max_depth": [None, 5, 10, 15],
    "min_samples_split": [2, 5, 10],
    "min_samples_leaf": [1, 2, 4]
}

# Grid search
grid_search = GridSearchCV(
    estimator=rf,
    param_grid=param_grid,
    cv=cv,
    scoring="accuracy",
    n_jobs=-1
)

# Train and test all combinations
grid_search.fit(X_train, y_train)

# Best parameters
print("Best Parameters:")
print(grid_search.best_params_)

# Best cross-validation score
print("\nBest Cross-Validation Accuracy:")
print(grid_search.best_score_)

print("\nBest Cross-Validation Accuracy (%):")
print(grid_search.best_score_ * 100)

Best Parameters:
{'max_depth': None, 'min_samples_leaf': 1, 'min_samples_split': 2, 'n_estimators': 50}

Best Cross-Validation Accuracy:
0.9400000000000001

Best Cross-Validation Accuracy (%):
94.0

In [65]:
# ============================================
# FINAL TEST OF TUNED RANDOM FOREST
# ============================================

from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix
)

# Get the best model found during tuning
best_rf = grid_search.best_estimator_

# Predict on the untouched test data
final_pred = best_rf.predict(X_test)

# Calculate final accuracy
final_accuracy = accuracy_score(y_test, final_pred)

print("Final Test Accuracy:")
print(final_accuracy)

print("\nFinal Test Accuracy (%):")
print(final_accuracy * 100)

# Classification report
print("\nClassification Report:")
print(classification_report(y_test, final_pred))

# Confusion matrix
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, final_pred))

Final Test Accuracy:
0.9215686274509803

Final Test Accuracy (%):
92.15686274509804

Classification Report:
              precision    recall  f1-score   support

           0       0.80      1.00      0.89        16
           1       1.00      0.89      0.94        35

    accuracy                           0.92        51
   macro avg       0.90      0.94      0.91        51
weighted avg       0.94      0.92      0.92        51


Confusion Matrix:
[[16  0]
 [ 4 31]]

In [66]:
# ============================================
# FEATURE IMPORTANCE
# ============================================

import pandas as pd

# Get feature importance from the tuned Random Forest
importance = best_rf.feature_importances_

# Create a table
feature_importance = pd.DataFrame({
    "Feature": X_train.columns,
    "Importance": importance
})

# Sort from highest to lowest
feature_importance = feature_importance.sort_values(
    by="Importance",
    ascending=False
)

print(feature_importance)

               Feature  Importance
2             Polyuria    0.234918
3           Polydipsia    0.186069
0                  Age    0.104931
1               Gender    0.073264
10        Irritability    0.056696
4   sudden weight loss    0.048999
6           Polyphagia    0.040840
8      visual blurring    0.035373
13    muscle stiffness    0.034089
12     partial paresis    0.033717
11     delayed healing    0.033528
14            Alopecia    0.031090
7       Genital thrush    0.025167
15             Obesity    0.025144
9              Itching    0.024383
5             weakness    0.011791

In [67]:
import joblib

joblib.dump(best_rf, "diabetes_model.pkl")

print("Model saved successfully!")

Model saved successfully!

In [68]:
feature_names = X.columns.tolist()

joblib.dump(feature_names, "feature_names.pkl")

print("Feature names saved!")
print(feature_names)

Feature names saved!
['Age', 'Gender', 'Polyuria', 'Polydipsia', 'sudden weight loss', 'weakness', 'Polyphagia', 'Genital thrush', 'visual blurring', 'Itching', 'Irritability', 'delayed healing', 'partial paresis', 'muscle stiffness', 'Alopecia', 'Obesity']

In [70]:
# ============================================
#create prediction function
# ============================================

def predict_diabetes(
    age,
    gender,
    polyuria,
    polydipsia,
    sudden_weight_loss,
    weakness,
    polyphagia,
    genital_thrush,
    visual_blurring,
    itching,
    irritability,
    delayed_healing,
    partial_paresis,
    muscle_stiffness,
    alopecia,
    obesity
):

    # Convert user input into the same numerical format
    input_data = pd.DataFrame([{
        "Age": age,
        "Gender": 1 if gender == "Male" else 0,
        "Polyuria": 1 if polyuria == "Yes" else 0,
        "Polydipsia": 1 if polydipsia == "Yes" else 0,
        "sudden weight loss": 1 if sudden_weight_loss == "Yes" else 0,
        "weakness": 1 if weakness == "Yes" else 0,
        "Polyphagia": 1 if polyphagia == "Yes" else 0,
        "Genital thrush": 1 if genital_thrush == "Yes" else 0,
        "visual blurring": 1 if visual_blurring == "Yes" else 0,
        "Itching": 1 if itching == "Yes" else 0,
        "Irritability": 1 if irritability == "Yes" else 0,
        "delayed healing": 1 if delayed_healing == "Yes" else 0,
        "partial paresis": 1 if partial_paresis == "Yes" else 0,
        "muscle stiffness": 1 if muscle_stiffness == "Yes" else 0,
        "Alopecia": 1 if alopecia == "Yes" else 0,
        "Obesity": 1 if obesity == "Yes" else 0
    }])

    # Make prediction
    prediction = best_rf.predict(input_data)[0]

    # Convert numerical prediction back to text
    if prediction == 1:
        result = "Positive"
    else:
        result = "Negative"

    return result

In [71]:
#=====================
#test prediction model
#=====================
result = predict_diabetes(
    age=45,
    gender="Male",
    polyuria="Yes",
    polydipsia="Yes",
    sudden_weight_loss="Yes",
    weakness="Yes",
    polyphagia="Yes",
    genital_thrush="No",
    visual_blurring="Yes",
    itching="No",
    irritability="Yes",
    delayed_healing="Yes",
    partial_paresis="No",
    muscle_stiffness="No",
    alopecia="No",
    obesity="Yes"
)

print("Prediction:", result)

Prediction: Positive

In [74]:
#==========================
#add prediction probability
#==========================
def predict_diabetes(
    age,
    gender,
    polyuria,
    polydipsia,
    sudden_weight_loss,
    weakness,
    polyphagia,
    genital_thrush,
    visual_blurring,
    itching,
    irritability,
    delayed_healing,
    partial_paresis,
    muscle_stiffness,
    alopecia,
    obesity
):

    input_data = pd.DataFrame([{
        "Age": age,
        "Gender": 1 if gender == "Male" else 0,
        "Polyuria": 1 if polyuria == "Yes" else 0,
        "Polydipsia": 1 if polydipsia == "Yes" else 0,
        "sudden weight loss": 1 if sudden_weight_loss == "Yes" else 0,
        "weakness": 1 if weakness == "Yes" else 0,
        "Polyphagia": 1 if polyphagia == "Yes" else 0,
        "Genital thrush": 1 if genital_thrush == "Yes" else 0,
        "visual blurring": 1 if visual_blurring == "Yes" else 0,
        "Itching": 1 if itching == "Yes" else 0,
        "Irritability": 1 if irritability == "Yes" else 0,
        "delayed healing": 1 if delayed_healing == "Yes" else 0,
        "partial paresis": 1 if partial_paresis == "Yes" else 0,
        "muscle stiffness": 1 if muscle_stiffness == "Yes" else 0,
        "Alopecia": 1 if alopecia == "Yes" else 0,
        "Obesity": 1 if obesity == "Yes" else 0
    }])

    prediction = best_rf.predict(input_data)[0]

    probabilities = best_rf.predict_proba(input_data)[0]

    negative_probability = probabilities[0]
    positive_probability = probabilities[1]

    if prediction == 1:
        result = "Positive"
    else:
        result = "Negative"

    return result, negative_probability, positive_probability

In [73]:
result, negative_prob, positive_prob = predict_diabetes(
    age=45,
    gender="Male",
    polyuria="Yes",
    polydipsia="Yes",
    sudden_weight_loss="Yes",
    weakness="Yes",
    polyphagia="Yes",
    genital_thrush="No",
    visual_blurring="Yes",
    itching="No",
    irritability="Yes",
    delayed_healing="Yes",
    partial_paresis="No",
    muscle_stiffness="No",
    alopecia="No",
    obesity="Yes"
)

print("Prediction:", result)
print("Negative probability:", round(negative_prob * 100, 2), "%")
print("Positive probability:", round(positive_prob * 100, 2), "%")

Prediction: Positive
Negative probability: 4.0 %
Positive probability: 96.0 %